public enum NodeType {
    PROGRAM,
    STATEMENTS,
    STATEMENT,
    MESSAGESTATEMENT,
    INPUTSTATEMENT,
    ASSIGNMENTSTATEMENT,
    NEWLINESTATEMENT,
    SHOWSTATMENT,
    VARIABLE,
    EXPRESSION,
    TERM,
    FACTOR,
    NUMBER,
    ;
}
